### ISSUE TITLE
Getting the Current User

### ISSUE THREAD

**Issue by tfasano1** [pattmax00/GoWeb#4]
Excuse my poor Go knowledge, but I'm trying to display the current user's username on the home page using ShowHome(), in `controllers/getcontrollers.go`. Here's the code:

```go
func (getController *GetController) ShowHome(w http.ResponseWriter, r *http.Request) {
	type dataStruct struct {
		Test string
	}

	user, err := models.GetCurrentUser(getController.App, r);

	if err != nil {
	    user.Username = "darkness my old friend"
	}

	data := dataStruct{
	    Test: "Hello " + user.Username + "!",
	}

	templating.RenderTemplate(getController.App, w, "templates/pages/home.html", data)
}
```

A valid user is never returned from GetCurrentUser(). At first I thought it was a database problem, but it seems to be working fine. Is there something wrong with this go code? Thank you.

**Comment by pattmax00** [comment]
Good catch. I need to be better about testing those unused functions. I made a fix you can grab from master. 71d3bd7
