### ISSUE TITLE
REST Methods

### ISSUE THREAD

**Issue by tfasano1** [pattmax00/GoWeb#5]
From my research of the docs, `net/http` only handles GET and POST requests. Are there plans to use a mux which can handle PUT or DELETE requests?  You can trigger these requests from the templates just like any other form element using [htmx](https://htmx.org).

Using Post for deleting/updating will have consequences, since Post isn't idempotent.

**Comment by pattmax00** [comment]
I think you have to make PUT and DELETE requests with fetch
https://stackoverflow.com/a/68529248

**Comment by pattmax00** [comment]
New controller files should be named and created according to their purpose like `userController.go` I should change this and make it more clear in the default setup.

For routes, I suggest having a couple big master files, so it's easy to find the logic associated with them (eg. user reports an error on page `/url/thing/example`).

So for your use case I'd say make a new routes file called `multiMethodRoutes.go` (or whatever name you find better) and those can be tied to Go functions that are tied to a switch statement like in the example you gave. It's really all just a naming convention though, you could define these routes in `getRoutes.go` or `postRoutes.go` but that would be improper.

Hopefully this all makes sense.
